### ISSUE TITLE
How is cancellation going to be used?

### ISSUE THREAD

**Issue by domenic** [slightlyoff/Promises#1]
This is a fairly innovative approach to cancellation. However, I'm not sure it allows the use cases one might hope for. E.g. how could a future-returning XHR method allow you to cancel the XHR?

``` js
var xhrFuture = doXhrPostWithLotsOfData(options);

xhrFuture.then(function (whatever, resolverForXhrFuture) {
    // I want to call `resolverForXhrFuture.cancel` to cancel the POST upload,
    // but I'm not even called until way after it's finished!
});
```

Some examples of how you anticipate cancellation working would help clarity a lot.

**Comment by slightlyoff** [comment]
Cancellation is a feature of the resolver of the operation. In this case, you'd imagine that the doXhrPostWithLotsOfData() method might hand back a reference to the Resolver instance, not the Future. Similarly, the Resolver/Future that are auto-generated by the then() call is the one you can cancel with the resolverForXhrFuture. Canceling the Post requires that doXhr**\* hands back a Resolver or manages to add the cancel() capability to the Future.

**Comment by domenic** [comment]
Ah, OK. I think I was misled by the paragraph talking about how the second parameter to `onaccepted` (i.e. `resolverForXhrFuture` in this example) would be useful for cancellation. Now it makes sense.
