### ISSUE TITLE
`this` binding for `then()` callbacks?

### ISSUE THREAD

**Issue by slightlyoff** [slightlyoff/Promises#10]
Should callbacks for `.then()` be invoked as though they are:

``` js
  callback.call(future, valueOrError);
```

?

I think yes, but am flexible.

**Comment by domenic** [comment]
I think using `this` as an implicit zeroth parameter is an anti-pattern, but am not sure how common such an opinion is. I guess there is DOM precedent for it (although not ECMAScript precedent).

**Comment by slightlyoff** [comment]
I can't speak for how common it is, but I for one prefer `.call()` to contextualize otherwise unbound `this` in some meaningful way. I prefer a "soft call" and "soft bind" as well, but they're not something on the table for this discussion.

**Comment by wycats** [comment]
This would be a lot more useful if the binding was configurable, but unfortunately the signature does not permit that. It's probably my number one annoyance with using Promises in Ember these days :frowning:

**Comment by annevk** [comment]
http://dom.spec.whatwg.org/#concept-event-listener-invoke Look for "callback this value". Also http://dev.w3.org/2006/webapi/WebIDL/#dfn-callback-this-value That is used in a number of places.

**Comment by sicking** [comment]
I like the idea of using the future as the `this`, though I understand the distaste for using `this` as a hidden parameter.

But it does seem more useful than using the global as `this` which would be the only other sensible thing I think?

And adding additional what-to-use-as-this parameters everywhere where you can register a callback seems like a language issue. If .bind() isn't good enough it then maybe ES needs to grow new syntax?

**Comment by erights** [comment]
I don't think global-as-this is ever reasonable except for methods of window. Generally, the preference that's been expressed by myself and others is to pass "undefined" as this for these callbacks. (Of course, if the callback isn't strict, it'll coerce the undefined to the global object, but that's just one of the problems with calling non-strict functions as functions.)

**Comment by sicking** [comment]
Sure. But passing undefined (or null) as `this` doesn't seem any more useful than passing the Future.

**Comment by domenic** [comment]
But it makes it clear that the callbacks are functions, not methods.

**Comment by annevk** [comment]
If the Future only has then() / done() methods it might not relevant to have the Future available.

**Comment by slightlyoff** [comment]
I'm going to add text that "this" is set to the `Future` instance. We can fight about it more if there are strong objections = )
