### ISSUE TITLE
Making this repo public...when?

### ISSUE THREAD

**Issue by slightlyoff** [slightlyoff/Promises#12]
I think we're pretty close to consensus on the most pressing issues (modulo #11, the MOST IMPORTANT ISSUE OF ALL). The polyfill and tests aren't done and I won't likley have time to get to them until next week at the earliest. What is the feeling of those who have been paying attention to this repo about opening it up now? Is there a compelling reason to wait any longer?

**Comment by annevk** [comment]
I'd like to share it with others.
