### ISSUE TITLE
No need for both cancel, reject and timeout

### ISSUE THREAD

**Issue by DavidBruant** [slightlyoff/Promises#15]
Since reject can take any value, that should be sufficient

**Comment by DavidBruant** [comment]
The `rejected` would go away too.

**Comment by slightlyoff** [comment]
common patterns deserve API.

**Comment by DavidBruant** [comment]
Can you show some code where these patterns are used and having these methods would have improves readability (or improve anything really)?
Also, `cancel` and `timeout` would both be aliases of `reject` called with no argument. Since they can both be implemented on top of `reject` how is it not an instance of library code as in #16 ? Specifically, for `timeout` which would have better being implemented on top of [Q.delay and Q.race](http://wiki.ecmascript.org/doku.php?id=strawman:concurrency#q.delay)
Finally, neither `cancel` nor  `timeout` are reflected at runtime. The only thing that exists is a "rejected" state.

If these patterns are so common and the distinction matters, a better solution would be to provide built-in error constructors in my opinion:

``` js
//prom.timeout would become an alias of:
prom.reject(new TimeoutError('you timedout, bro'))

// and cancel an alias of:
prom.reject(new CancelError('you timedout, bro'))
```

or something equivalent.

**Comment by DavidBruant** [comment]
`common patterns deserve API.`
At the same time, when would the list stop? If 2 other patterns are discovered common, will they be added as rejection/acceptation methods? Extension through error value/value seems more appropriate.

**Comment by DavidBruant** [comment]
I should have read the proposal more carefully, sorry about that.

**Comment by slightlyoff** [comment]
Does that mean you understand the desugaring now and think it's fine? Or understand it and think it's bad?

**Comment by DavidBruant** [comment]
I understand it and think it's not harmful. I don't think I'll ever use that personally because I think discriminating the source of rejection through the error value is enough. But if others find a use for it, that's fine.

**Comment by slightlyoff** [comment]
Great, thanks!
