### ISSUE TITLE
Add an equivalent to Q.all

### ISSUE THREAD

**Issue by DavidBruant** [slightlyoff/Promises#16]
From experience, that's necessary to use promises effectively.
Yes, people can write it as a library... in which they'll do off-by-one errors or equivalent.

**Comment by arv** [comment]
I agree that we need some standard library functions to work with futures but this can wait a bit

**Comment by slightlyoff** [comment]
I agree it's necessary eventually, but perhaps not in the first rev. Got a suggested API signature?

**Comment by domenic** [comment]
For the API signature: arrays are more ES5-friendly, variadic slightly nicer in ES6. That is,

``` js
// array version, ES5 and ES6
Q.all(myArray)
Q.all([a, b, c]) // this is more common and slightly uglier

// variadic version, ES5
Q.all.apply(null, myArray) // ugh
Q.all(a, b, c)

// variadic version, ES6
Q.all(...myArray)
Q.all(a, b, c)
```

**Comment by arv** [comment]
We should be designing for the future. So, I prefer variadic.

On Wed, Feb 6, 2013 at 5:27 PM, Domenic Denicola
notifications@github.comwrote:

> For the API signature: arrays are more ES5-friendly, variadic slightly
> nicer in ES6. That is,
> 
> // array version, ES5 and ES6Q.all(myArray)Q.all([a, b, c]) // this is more common and slightly uglier
> // variadic version, ES5Q.all.apply(null, myArray) // ughQ.all(a, b, c)
> // variadic version, ES6Q.all(...myArray)Q.all(a, b, c)
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/slightlyoff/DOMFuture/issues/16#issuecomment-13209253.

## 

erik

**Comment by DavidBruant** [comment]
I agree with @arv; variadic, let's design for the Future (puns are going to be endless with the name future). We can assume that engines implementing Futures will support the spread notation soon enough.
As far as API or signature, I'd say static function on `Future` like:

``` js
Future.all(f1, f2, f3)
// or maybe
Future.combine(f1, f2, f3)
```

**Comment by slightlyoff** [comment]
I'm fine with a variadic static method...what's the exact semantic? Can you write a small test that explains the behavior?

**Comment by domenic** [comment]
Here's the essential implementation:

https://github.com/then/all/blob/master/index.js#L19-L38

Basically, returns a promise that:
- Is rejected with the first rejection reason that occurs, or
- If all promises are fulfilled, fulfill with an array containing their fulfillment values

**Comment by jakearchibald** [comment]
``` javascript
Q.all([a, b, c]) // this is more common and slightly uglier
```

Are we sure this is the common case? In my experience I'm mostly calling `.all` on an array of futures.

**Comment by DavidBruant** [comment]
@jakearchibald can you further explain what you understood from that quote and what you disagree on? You're saying "on an array of futures" and that's what the line you're quoting does from what I understand.

**Comment by jakearchibald** [comment]
Ah yes, sorry, I mean I tend to build the array as part of an extra step, usually because the number of entries is the array varies, so my common case is more like:

``` javascript
Q.all(myArray)
```

**Comment by erights** [comment]
My initial spec http://wiki.ecmascript.org/doku.php?id=strawman:concurrency and implementation http://code.google.com/p/es-lab/source/browse/trunk/src/ses/makeQ.js of Q was variadic, because I was thinking purely in terms of an ES6 future with "...". Kris Kowal convinced me to change to the single array parameter because it is 1) much more convenient for transitional pre-ES6 usage, which will continue for years, and 2) only very marginally less convenient for the ES6 future, costing only an extra pair of square brackets. Since making the switch, I have never minded the extra square brackets.

I made the same change to Q.race. Q.join I left variadic, since by far and away the common case is to use it with exactly two arguments. In fact, I've never come across a need to Q.join any number of promises other than two.

**Comment by DavidBruant** [comment]
Would there be restrictions to make the method being both variadic and accepting an array? The beginning of the internal implementation would be something like:

``` js
function all(){
  var futures = [].slice.call(arguments);
  if(futures.length === 1 && Array.isArray(futures[0]))
    futures = futures[0];
  // now futures is an array of promises regardless of the original arguments
}
```

it'd be both usable for ES6 and pre-ES6.

**Comment by arv** [comment]
Lets not chicken out just yet. DOM is using rest args now and people already know how to use apply. Lets design for a better future.

**Comment by erights** [comment]
@arv I have chickened out as you put it. As you know, I'm generally more future focussed than most. But I've tried this one both ways and the benefits of varargs here really are marginal. And any promise library must catch on among ES5 users, to become de facto std, by the time ES7 is ready to make it de jure. Q's decision is based on experience and feedback from actual usage.

**Comment by erights** [comment]
@DavidBruant I don't understand how this could work. Remember, the arguments to Q.all are not necessarily promises. Your Q.all might be called in a varargs manner with a single object that happens to be an array. Your Q.all would misclassify it as an array of arguments. This kind of ambiguity in an API is always bad.

**Comment by DavidBruant** [comment]
@erights I see. I imagined there was a good reason for it not being suggested earlier, but I couldn't put my finger on it. Taking back the idea then. Thanks.

To share a little bit of experience with Q.all, I've found myself naturally (without prior experience with any other promise library) writing the "list" or promises without bracket and wasted a lot of time understanding I had forgotten the brackets. That's just anecdotal experience, but relevant to the discussion, I think.

I usually hate when I want to make an API better and I'm answered "you can build what you want as a library", but maybe the array case could be added by a (one-liner) "library":

``` js
DOMFuture.allArr = function(arrFs){ return DOMFuture.all.apply(undefined, arrFs) }
```

Regarding pre-ES6 usage, an ES6->ES3 compiler can turn:

``` js
DOMFuture.all(...futures)
```

into

``` js
DOMFuture.all.apply(DOMFuture, futures);
// DOMFuture as |this| isn't necessary.
// That's just what a good default choice a ES6->ES3 compiler could make
```

There would be minor limitations like if `Function.prototype.apply` is overridden, etc. But people doing that really aren't helping themselves, so even the library above wouldn't work.

**Comment by annevk** [comment]
I'm with @arv. Lets use only vararg. The DOM is adopting this pattern and I'd really rather not complicate all those APIs by also making them accept arrays which JavaScript will already provide for by using the ...array syntax.

**Comment by erights** [comment]
@domenic @kriskowal Is there any transition strategy which would let Q.all, Q.race, etc migrate back to a varargs API without breaking all its clients? If @DavidBruant's testing suggestion had worked, that could have bridged this issue. But otherwise we seem stuck. Ideas?

@arv @annevk @DavidBruant Would you consider names other than "all" and "race" for the varargs variety? If not, do you have any suggestions for how Q could manage this transition?

**Comment by annevk** [comment]
@erights I thought the idea was for these methods to be put on Future as static methods.

**Comment by DavidBruant** [comment]
@erights I wonder why Q would need to change at all. Q is a library that has its API, known by whoever uses it. DOMFuture will have its API.
I've used [`jQuery.when`](http://api.jquery.com/jQuery.when/) (variadic) and `Q.all` and never really confused one for the other. (I've had a tendency to forget about the brackets in Q but that was before trying jQuery).

Even regardless of this whole discussion, one idea on the Q side would be to throw an error if more than one argument is passed (that would have saved me some time)

But besides that, I don't see why Q would need to change.

**Comment by erights** [comment]
@annevk Yes. "all" is a static method on Q as well.

@DavidBruant I think it would be terribly confusing for Q and Future to be generally alike, and for their static "all" methods to have the same semantics, _except_ that Q.all takes an array argument but Future.all is variadic. If we can't get Future to change, then we need to change Q. Hence my question.

Having Q.all throw on more than one arg would help catch errors, exactly in the other case: where we keep Q.all as it is. It doesn't help in making a transition to a variadic Q.all.

**Comment by DavidBruant** [comment]
@erights `all` is written in stone for DOMFuture as far as I know.
Some alternatives could be `combine`, `sync`.
"sync" may sounds confusing, but I think it indicates well the intent of "waiting" until all futures are resolved before continuing, making it a synchronization mechanism.

**Comment by annevk** [comment]
@erights I don't think it matters much if a library today follows a slightly different pattern. Future is from the future and will see much more widespread adoption. There'll be some transition cost maybe, but nothing much to worry about.

**Comment by slightlyoff** [comment]
I'm with @annevk and @arv on this. Not chickening out = )

**Comment by domenic** [comment]
I think it would be unfortunate for Q and Future to be misaligned in this area, but not the end of the world. (As for mitigation solutions, @erights: the only one I can think of is waiting for a major version bump in Q, and switching. Which is probably feasible.)

However, it's a good opportunity to make sure "all" is the name we would want in Future. Just today a coworker remarked that it's not intuitive. I'm personally a fan of "when"; I also think we could repurpose "join," which is currently used in @erights's concurrency strawman for a different meaning, but not in Q itself. ("join" is used in when.js as a variadic "all" actually.) My preference for "when" over "join" is that "when" sounds better in the single-argument case.

**Comment by annevk** [comment]
Future.when(...) works for me.

**Comment by kriskowal** [comment]
For the record, the concurrency strawman @erights wrote originally called for a variadic `Q.all(...values)`, but, after giving it a reasonable chance, two problems cropped up:
1. ES<5 doesn't have a spread operator. Having variable and fixed numbers of promises to synchronize are both common cases. It is less painful to add brackets in the fixed-length case than it is to add the variadic spread incantation. It is in the scope of Q’s charter to make promises enticing in engines of today and yesteryear in hope that they are even nicer in the engines of tomorrow.
2. A convention emerged that Q.x(p, …args) is usually equivalent to Q(p).x(…args). Consider this usage:

``` javascript
p1.then(function (r1) {
    return [r1, p2, p3];
})
.all()
.then(function ([r1, r2, r3]) {
})
```

It makes sense for Q.all(ps) to have the Q(ps).all() dual. It also makes sense for promises to have a 1 to 1 correspondence with return values or thrown exceptions. Therefore, it makes sense for Q.all to operate on promises for arrays of promises.

**Comment by erights** [comment]
On Feb 20, 2013, at 8:43 AM, Anne van Kesteren notifications@github.com wrote:

> Future.when(...) works for me.

Me too.

**Comment by slightlyoff** [comment]
So we seem to be mostly aligned around `Future.when()`. I'll add it when (har har) there's reasonable consensus around the semantics...are there open debates there?

Also, note that `Future` and `EventedFuture` have been split out, so class-side inheritance is once again our friend = )

**Comment by rkatic** [comment]
A nice aspect of the non-variadic `Q.all` is that it is clear that the `onFulfilled` handler will be eventually called with a single array argument. Infect, to spread resolved promises, you have to do that explicitly:

```
Q.all([promiseA, promiseB]).spread(function(A, B) {...});
```

Although a variadic `when` is read nicely with a single promise, it only have sense if resolved promises will be implicitly spread as arguments of the `onFulfilled` handler. A variadic `join` could reduce this expectation.

**Comment by annevk** [comment]
This is in the DOM standard now as Future.every().

**Comment by kriskowal** [comment]
@annevk, Future.every does fit idiomatically in the presence of Array#every, but implies the existence of a guard function. Does it support one?

**Comment by slightlyoff** [comment]
I don't understand what you mean by "guard function" specifically, but if the question is "does the pun with names extend to argument types and positions?", the answer is "no".

That might argue for calling it `.all()`, but I'm not fussed either way.
