### ISSUE TITLE
No need to inherit from EventTarget

### ISSUE THREAD

**Issue by DavidBruant** [slightlyoff/Promises#17]
The `.then` and `.done` already take care of registering callbacks.
Futures can be seen as an idomatic construct built on top of promises, paving the cowpath of a very recurrent pattern (make a request which succeeds or fail)

**Comment by slightlyoff** [comment]
Subclassing from EventTarget provides a simple extension point for the addition of non-callback lifecycle notification for many common DOM operations (progress in XHR, e.g.).

**Comment by DavidBruant** [comment]
Good point.
Though are the accept/reject events necessary? especially given that manual dispatch is supposed to throw an error?

**Comment by slightlyoff** [comment]
They're useful conveniences. If you're writing in one style, you should be able to stay in that style.

**Comment by DavidBruant** [comment]
Fair enough.
