### ISSUE TITLE
Add a .fail method

### ISSUE THREAD

**Issue by DavidBruant** [slightlyoff/Promises#18]
From experience with the Q library, when the 2 callbacks of the then are long, it isn't very clear where the onrejected starts.
Adding a .fail(function) gives a more declarative impression and is less ambiguous (doesn't need to keep track of indentation of a long function)

**Comment by domenic** [comment]
Better spelled `catch`.

**Comment by DavidBruant** [comment]
I'm concerned with having a declarative-looking thing to plug an error-case callback to.
I like `fail`, but I'm fine with `catch` :-) The exact name isn't something I'll fight over.

**Comment by slightlyoff** [comment]
If there's agreement on `.catch (or at least acquiescence), would gladly merge a pull for it.

**Comment by jakearchibald** [comment]
I like this. In the `NavigationController` stuff you often want to handle failures but are less interested in success. `.then(undefined, func)` doesn't read as well as `.catch(func)` in these cases.

**Comment by slightlyoff** [comment]
.catch() has been added: https://github.com/slightlyoff/DOMFuture/commit/b3d816be909275c089175b72f84a4df4088d8973
