### ISSUE TITLE
Throwing non-errors

### ISSUE THREAD

**Issue by domenic** [slightlyoff/Promises#2]
It seems from the IDL that resolvers are not going to allow rejecting with non-`Error`s. OK. But what about this sentence?

> If the callback throws, resolve the returned future with an Error

What if the callback throws a non-`Error`? E.g.

``` js
future.then(undefined, function () {
    throw 5;
});
```

or worse,

``` js
future.then(undefined, function () {
    throw undefined;
});
```

?

**Comment by slightlyoff** [comment]
It's a good point. What do you think it _should_ do?

**Comment by domenic** [comment]
The rejection reason (error, I think it's called now?) should be `5` or `undefined`.

**Comment by jakearchibald** [comment]
+1, any thrown value should be passed to the rejection call back (as it is in _onResolution)

**Comment by slightlyoff** [comment]
Changing the text to indicate that this is how it works. Thanks for spotting it!

**Comment by slightlyoff** [comment]
Fixed: https://github.com/slightlyoff/DOMFuture/commit/534379985228bed952609f9b9b991f07f59f7f26#L0R185
