### ISSUE TITLE
New WebIDL notation for DOMFuture

### ISSUE THREAD

**Issue by DavidBruant** [slightlyoff/Promises#20]
Having documented a bunch of WebAPIs implemented in FirefoxOS, I've noticed that a lot of methods return a DOMRequest. But nobody cares. What people care about is not the value they get immediatly, but the value the get eventually. It would be good if WebIDL was expanded to accept the following notation:

```
interface I{
    DOMFuture<File> getFile(in DOMString name);
}
```

I'm not 100% sure it's relevant for this repo, but it'd be good to keep this in mind.

**Comment by slightlyoff** [comment]
Sounds like a job for Cameron. Have you pinged him about this?

I too am bugged by the lack of specificity in how the future return type is undocumented once a Future comes into play.

**Comment by annevk** [comment]
I think if Future becomes a native ECMAScript type it could also become a native IDL type and we could give such objects syntax like this.

**Comment by wycats** [comment]
@annevk I don't think we would necessarily want to mandate that APIs that return compatible Futures actually use the native ES type.

**Comment by annevk** [comment]
I filed a bug on WebIDL. If that does not solve it we can revisit this in JSIDL.
