### ISSUE TITLE
Fast forwarding un-handled values

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/Promises#3]
"Chaining fast-forwards un-handled values to the end of the chain." - is it always the end of the chain?

``` javascript
asyncTask().then(function(val, nextResolver) {
    throw new Error("BAM!");
}).then(function() {
    console.log('Ok 1')
}).then(function() {
    console.log('Ok 2');
}, function() {
    console.log('Error 1');
}).done(function() {
    console.log('Ok 3');
}, function() {
    console.log('Error 2');
});
```

What gets logged here?

**Comment by slightlyoff** [comment]
You're right, it's not always to the end of the chain, it's to whatever next in the chain handles that particular resolution disposition. In this case, you'll log "Error 1". Updating the text to be clearer about this.
