### ISSUE TITLE
Implement promises-tests.

### ISSUE THREAD

**Issue by slightlyoff** [slightlyoff/Promises#38]
Background: https://github.com/domenic/promise-tests

It's painful to see that @domenic has bought off on Mocha/Sinon and the shit-show that is Node testing, but the test suite is comprehensive and we should ensure that, insofar as Promises A+ doesn't diverge further from DOMFuture, that we support its tests.

**Comment by domenic** [comment]
That repo is obsolete and replaced by https://github.com/promises-aplus/promises-tests, which has much better coverage.

**Comment by slightlyoff** [comment]
Thanks! Will use that instead.

**Comment by slightlyoff** [comment]
@domenic : I'm seeing 2 issues now that I've got the tests wired up under node:
1. The polyfill follows the spec and throws an `AlreadyResolved` exception on multiple resolution attempts from the same resolver. The test suite barfs on this.
2. I don't understand something about how the pseudo-promise tests from `3.2.6.3.*` are meant to work. I've removed the arity check in `isThenable`, but continue to get errors of the sort:

```
  1) 3.2.6: `then` must return a promise: `promise2 = promise1.then(onFulfilled, onRejected)` 3.2.6.3: If either `onFulfilled` or `onRejected` returns a promise (call it `returnedPromise`), `promise2` must assume the state of `returnedPromise` 3.2.6.3.2: If/when `returnedPromise` is fulfilled, `promise2` must be fulfilled with the same value. `promise1` is fulfilled, and `returnedPromise` is: a pseudo-promise:
     Error: timeout of 200ms exceeded
      at Object.<anonymous> (/projects/DOMFuture/polyfill/third_party/promises-tests/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.list.ontimeout (timers.js:101:19)
```

**Comment by domenic** [comment]
As to 1, your adapter will need to wrap a `try`/`catch` around it. The `adapter.pending().fulfill` and `adapter.pending().reject` methods are not meant to throw. I will add that to the readme.

For 2, I'll have to look into it further, but the intent is that returning a thenable (nee pseudo-promise) adopts the state of the thenable. In this case the thenable's state is fulfilled with `sentinel`, so `returnedPromise`'s state should eventually be the same (fulfilled with `sentinel`).

**Comment by slightlyoff** [comment]
I see. I'm not sure that fixing 1 is easy, but I was using `.done()` which broke compat. Fixed now. Thanks.

**Comment by domenic** [comment]
Did the fix for 1, by just wrapping the calls to `resolve` and `reject`.

**Comment by slightlyoff** [comment]
I see...had tried that before but I think perhaps some other issue was getting in the way. Thanks so much!
