### ISSUE TITLE
Nullable onaccept

### ISSUE THREAD

**Issue by darobin** [slightlyoff/Promises#45]
We currently have:

```
Future then(optional AnyCallback onaccept, optional AnyCallback onreject);
```

My reading of WebIDL is that the above does not allow you to call:

```
fut.then(null, errCB);
```

("Web IDL operations do not support being called with omitted optional arguments unless all subsequent optional arguments are also omitted.")

I know that there's `catch` for that case, but it can lead to unpleasant code when you're getting the callbacks from somewhere else. To give an example, I bumped into that issue recently in which I had to support an interface that could accept success and error callbacks and needed to return a future. I ended up with the equivalent of:

``` js
function (foo, successCB, errorCB) {
    var fut = new Future();
    if (errorCB && !successCB) fut = fut.catch(errorCB);
    else if (successCB) fut = fut.then(successCB, errorCB);
   return fut;
}
```

Not dreadful, but ugly and annoying. Instead we could have:

```
Future then([TreatUndefinedAs=Null] optional AnyCallback? onaccept, [TreatUndefinedAs=Null] optional AnyCallback? onreject);
```

Or something along those lines.

**Comment by arv** [comment]
Maybe WebIDL needs to align with ES6 here? In ES6 you can pass `undefined` to use the default parameter value.

``` js
function f(x = 1, y = 2) {
  return x;
}
assert(f(undefined, 1) === 1);
```

**Comment by domenic** [comment]
In Promises/A+, we eventually agreed to allow any non-function to trigger the default behavior. [Long debate here](https://github.com/promises-aplus/promises-spec/issues/25) and also [here](https://github.com/promises-aplus/promises-spec/issues/25).

Useful data we gathered, trying to use the ES5 spec as precedence:
- `JSON.parse` and `JSON.stringify` take optional function parameters, and ignore non-`[[Callable]]`s.
- `Array.prototype.sort` takes an optional function parameter, and throws on non-`[[Callable]]`s except `undefined`. (In particular, it throws on `null`.)
- `Function.prototype.bind`, `call`, and `apply` all use both `null` and `undefined` to signal the default value for their `thisArg` parameter (which is not a function parameter, but is in some sense an optional parameter).

The conclusion that I and some others came to was that there are two coherent positions:
1. Any non-`[[Callable]]`s trigger default argument behavior.
2. Only `undefined` triggers default argument behavior; other non-`[[Callable]]`s throw a synchronous error.

With these in mind, we found option 2 unacceptable as it breaks the common pattern of `promise.then(null, onRejected)`. Thus we settled on option 1.

**Comment by sicking** [comment]
Yes, WebIDL definitely needs to be updated here.

I think you might still need to make the signature to `Future then(optional AnyCallback? onaccept, optional AnyCallback? onreject);`

**Comment by annevk** [comment]
Yes, there's no default argument so the undefined thingie does not apply.

**Comment by darobin** [comment]
@annevk if you do fut.then(opts.success, opts.error) with success undefined and error being a function, doesn't the undefined get stringified to "undefined" if there is no TreatUndefAs? I thought that was the case (and still read it like that) but admittedly it's not a part of WebIDL I've paid great attention to.

**Comment by annevk** [comment]
No, that's only if the argument is non-optional and takes a string (iirc).

**Comment by sicking** [comment]
If that's how WebIDL is currently defined, then that sounds like a bug in WebIDL. Any optional argument has a "default thingy". I.e. for any optional argument there is a defined behavior for what happens if that argument is not specified. That's the behavior that should be triggered when `undefined` is explicitly passed to that optional argument.

**Comment by slightlyoff** [comment]
If the IDL is confusing, we need to change it, and if there's no way to say what we mean in IDL, we need to simply stop using it. I think this all just argues for moving this to TypeScript or something more expressive. Implementations shouldn't suffer for this, so I'll do it soon if there aren't objections.

**Comment by annevk** [comment]
See http://lists.w3.org/Archives/Public/public-script-coord/2013JanMar/0349.html and http://lists.w3.org/Archives/Public/public-script-coord/2013JanMar/0351.html for why IDL is important. "Move this to TypeScript" just means more figuring out as to what "TypeScript" means and distracts from getting Future landed.

**Comment by darobin** [comment]
Agreed with @annevk. Forget the side-thread about WebIDL issues, just add ? to the first parameter's type.

**Comment by annevk** [comment]
The IDL is now in the DOM Standard and I think it does what we want.
