### ISSUE TITLE
Not installable via npm

### ISSUE THREAD

**Issue by dlongley** [slightlyoff/Promises#50]
npm requires that `package.json` be at the top-level a git repo for a node module. Could things be shifted around so that this command can be run successfully:

npm install git://github.com/slightlyoff/DOMFuture.git

One simple solution would be to just move the polyfill contents up a directory. These changes would also help people forking the repository and installing w/npm.

**Comment by slightlyoff** [comment]
I'd actually like to move the polyfill to a new repo, but I don't know of any simple way to do that. Do you?

**Comment by davidlehn** [comment]
The simple way is of course to just copy the files to a new repo. If you want to keep the DOMFuture history, you could create a new clean repo, push all of DOMFuture to it, then use git to delete old files and move polyfill files up to the top level (or however you wanted it to be organized).

**Comment by msporny** [comment]
You can also use git filter-branch if you want to preserve the history, but only of a particular directory or branch of the tree: http://git-scm.com/book/ch6-4.html#The-Nuclear-Option:-filter-branch

**Comment by slightlyoff** [comment]
Hrm. filter-branch looks good, but really permanent. I'd like to not clobber things that badly. I may, instead, re-arrange the repo so that the spec stuff is in a subdir and that the pollyfill moves up a level. That might resolve most of the issues.

**Comment by dlongley** [comment]
+1 @slightlyoff for swapping the spec stuff w/the polyfill.

**Comment by agoode** [comment]
Maybe rename to DOMPromises at the same time?

**Comment by dlongley** [comment]
This is almost a decade old and no longer relevant -- closing. :)
