### ISSUE TITLE
"catch" is a reserved word

### ISSUE THREAD

**Issue by cowwoc** [slightlyoff/Promises#60]
You cannot use "catch" as a function name because it is a reserved word. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Reserved_Words

In terms of practical implications, Netbeans (and possibly other IDEs) treat it as a reserved word and parse/format the code accordingly leading to improper parsing/formatting.

Please rename this method.

**Comment by arv** [comment]
It is completely valid to have a property named `catch`. This is part of ES5 and all browsers implement this correctly.

**Comment by cowwoc** [comment]
Thank you for the clarification. I filed a bug report with Netbeans: https://netbeans.org/bugzilla/show_bug.cgi?id=231163

**Comment by mounirlamouri** [comment]
FTR, using `.catch()` will force developers to actually do `foo['catch']()` otherwise older browsers will not even be able to parse the file.

**Comment by cowwoc** [comment]
How old is old? Meaning, what browsers/versions do you think are affected?

**Comment by mounirlamouri** [comment]
Affected browsers are:
Safari: <= 5.0 (working on 5.1)
IE: <= 8.0 (working on 9.0)
Opera: <= 11.5 (working on 11.6)

Tested on Firefox down to 3.0 and it is working.
Tested on Chrome down to 14.0 and it is working.
