### ISSUE TITLE
Calling dispatchEvent after resolution

### ISSUE THREAD

**Issue by domenic** [slightlyoff/Promises#8]
It's probably worth noting somewhere that calling dispatchEvent (with the future-related events) after resolution will fail in some way.

**Comment by slightlyoff** [comment]
Good point. Care to add it? You should be able to directly.

**Comment by domenic** [comment]
Sure; do you think a comment is the right mechanism then? Just wanted to make sure it was OK for comments to add requirements on the behavior of interfaces that are implemented (i.e. wanted to make sure there were no Liskov Substitution Principle requirements in WebIDL).

**Comment by slightlyoff** [comment]
I think the next step from prose is a polyfill with tests, so yeah, for now adding it to the comment block feels right.

**Comment by domenic** [comment]
Actually use of `dispatchEvent` should be disallowed entirely, as consumers of the future shouldn't be allowed to modify its state at all. In any case, added.

**Comment by slightlyoff** [comment]
Agreed. The only legit source for `dispatchEvent` is the callbacks vended in the `Future`'s callback. We should be careful to ensure that this is disallowed as well: `node.dispatchEvent.call(future, ...);`

**Comment by arv** [comment]
If we implement the EventTarget it is tempting for people to use it to dispatch other events. Maybe we should not implement the EventTarget interface, just implement addEventListener and removeEventListener?

**Comment by slightlyoff** [comment]
I think subclasses will absolutely add more events. So long as that works, I'm fine with whatever gets us to Point B.
